server:
  port: 8081
logging:
  config: classpath:logback.xml
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
#      appname: xxl-job-executor-sample
#      port: 9999
      logretentiondays: -1
#      ip:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
spring:
  dubbo:
    registry:
      id: zkserver
      protocol: zookeeper
      address: 10.20.88.191
      port: 2181
    application:
      name: xxl-job-executor
    base-package: com.xxl.job.executor.impl
    protocol:
      id: dubbo
      name: dubbo
      serialization: hessian2
      port: 43602
    provider:
      retries: -1
      accesslog: false
      token: true
      registry: zkserver
      protocol: dubbo-jvm
      timeout: 20000
    consumer:
      check: false